table Aktivita
	lineageTag: 9c62edf8-66b9-4384-aa33-a1c1a4ff5cb0

	column 'Prispevek ID'
		dataType: int64
		formatString: 0
		lineageTag: 3042b4bb-8375-4037-891c-3fec195c45e5
		summarizeBy: none
		sourceColumn: Prispevek ID

		annotation SummarizationSetBy = Automatic

	column 'Uzivatel ID'
		dataType: int64
		formatString: 0
		lineageTag: 06d12a2b-4e88-4fdf-aaca-9cd97379ac27
		summarizeBy: none
		sourceColumn: Uzivatel ID

		annotation SummarizationSetBy = Automatic

	column Vytvoreno
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 45d30f9d-9c4a-4f29-9b73-73fd9e76da8d
		summarizeBy: none
		sourceColumn: Vytvoreno

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Aktualizovano
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 778da638-81e8-41ce-a7fa-a3e468544a7f
		summarizeBy: none
		sourceColumn: Aktualizovano

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Ucet ID'
		dataType: int64
		formatString: 0
		lineageTag: a2325c80-4cb8-46e8-b33b-24ff94bb5e14
		summarizeBy: none
		sourceColumn: Ucet ID

		annotation SummarizationSetBy = Automatic

	column 'Transakce ID'
		dataType: int64
		formatString: 0
		lineageTag: 2fad6d64-2ab0-4f4b-8d23-93a777996e0e
		summarizeBy: none
		sourceColumn: Transakce ID

		annotation SummarizationSetBy = Automatic

	column Castka
		dataType: int64
		formatString: #,0
		lineageTag: 8d3a7b99-2adc-47c9-b8c4-6ed8c201363c
		summarizeBy: sum
		sourceColumn: Castka

		annotation SummarizationSetBy = Automatic

	partition Aktivita = m
		mode: import
		source =
				let
				    Source = Sql.Databases("arasynapse-ondemand.sql.azuresynapse.net"),
				    Amazonie = Source{[Name="Amazonie"]}[Data],
				    dwh_Aktivita = Amazonie{[Schema="dwh",Item="Aktivita"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dwh_Aktivita,{{"Vytvoreno", type date}, {"Aktualizovano", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

